### ISSUE TITLE
assets missing bowtie2_index files

### ISSUE THREAD

**Issue by albertY9367** [GuttmanLab/chipdip-pipeline#4]
In the current repo, assets directory does not contain the bowtie2_index files specified in config.yaml,
https://github.com/GuttmanLab/chipdip-pipeline/blob/1af597abdeab1e48dec8717181705595e6edd6c1/config.yaml#L32-L34

**Comment by bentyeh** [comment]
That's by design, since the indices are large (~3.9 GB for human GRCh38, ~3.6 GB for mouse mm10). The README provides [instructions](https://github.com/GuttmanLab/chipdip-pipeline/blob/main/README.md#index-bt2) for how to download the mouse and human indices.
